import { Project, Diagram, DiagramElement, Relationship } from '../types/uml';

export function createDefaultUniversityProject(): Project {
  const projectId = 'proj_uni_hr';

  // 1. CLASS DIAGRAM
  const classElements: DiagramElement[] = [
    {
      id: 'c_dept',
      type: 'CLASS',
      name: 'Department',
      x: 120,
      y: 80,
      width: 220,
      height: 160,
      stereotype: '<<entity>>',
      attributes: ['- deptId: String', '- name: String', '- budget: Double'],
      methods: ['+ getCourses(): List<Course>', '+ assignHead(prof: Professor)'],
      style: {
        fillColor: '#F0F9FF',
        borderColor: '#0284C7',
        textColor: '#0F172A',
        borderWidth: 2,
        borderStyle: 'solid',
        opacity: 1,
        fontSize: 13,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
      },
    },
    {
      id: 'c_prof',
      type: 'CLASS',
      name: 'Professor',
      x: 460,
      y: 80,
      width: 230,
      height: 180,
      attributes: ['- employeeId: String', '- title: AcademicRank', '- researchArea: String'],
      methods: ['+ teachCourse(c: Course)', '+ publishPaper(p: Paper)', '+ gradeExam(s: Student): Grade'],
      style: {
        fillColor: '#FEFCE8',
        borderColor: '#CA8A04',
        textColor: '#0F172A',
        borderWidth: 2,
        borderStyle: 'solid',
        opacity: 1,
        fontSize: 13,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
      },
    },
    {
      id: 'c_student',
      type: 'CLASS',
      name: 'Student',
      x: 120,
      y: 360,
      width: 230,
      height: 190,
      attributes: ['- studentId: String', '- gpa: Double', '- enrollmentDate: LocalDate'],
      methods: ['+ enrollIn(c: Course): Boolean', '+ submitAssignment(a: Work)', '+ calculateGpa(): Double'],
      style: {
        fillColor: '#ECFDF5',
        borderColor: '#059669',
        textColor: '#0F172A',
        borderWidth: 2,
        borderStyle: 'solid',
        opacity: 1,
        fontSize: 13,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
      },
    },
    {
      id: 'c_course',
      type: 'CLASS',
      name: 'Course',
      x: 460,
      y: 360,
      width: 230,
      height: 190,
      stereotype: '<<entity>>',
      attributes: ['- courseCode: String', '- credits: Int', '- maxCapacity: Int'],
      methods: ['+ hasSeatsAvailable(): Boolean', '+ registerStudent(s: Student)', '+ cancelCourse(): void'],
      style: {
        fillColor: '#F5F3FF',
        borderColor: '#7C3AED',
        textColor: '#0F172A',
        borderWidth: 2,
        borderStyle: 'solid',
        opacity: 1,
        fontSize: 13,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
      },
    },
    {
      id: 'c_interface',
      type: 'INTERFACE',
      name: 'Authenticable',
      x: 770,
      y: 220,
      width: 200,
      height: 130,
      stereotype: '<<interface>>',
      attributes: [],
      methods: ['+ login(token: String): AuthToken', '+ verifyMFA(): Boolean'],
      style: {
        fillColor: '#FFFBEB',
        borderColor: '#D97706',
        textColor: '#0F172A',
        borderWidth: 2,
        borderStyle: 'dashed',
        opacity: 1,
        fontSize: 13,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
      },
    },
  ];

  const classRelationships: Relationship[] = [
    {
      id: 'r_dept_prof',
      type: 'COMPOSITION',
      sourceId: 'c_dept',
      targetId: 'c_prof',
      label: 'employs',
      sourceMultiplicity: '1',
      targetMultiplicity: '1..*',
      sourceRole: 'faculty',
      targetRole: 'staff',
      routing: 'straight',
    },
    {
      id: 'r_dept_course',
      type: 'AGGREGATION',
      sourceId: 'c_dept',
      targetId: 'c_course',
      label: 'offers',
      sourceMultiplicity: '1',
      targetMultiplicity: '1..*',
      routing: 'straight',
    },
    {
      id: 'r_prof_course',
      type: 'ASSOCIATION',
      sourceId: 'c_prof',
      targetId: 'c_course',
      label: 'instructs',
      sourceMultiplicity: '1..*',
      targetMultiplicity: '0..*',
      routing: 'straight',
    },
    {
      id: 'r_student_course',
      type: 'ASSOCIATION',
      sourceId: 'c_student',
      targetId: 'c_course',
      label: 'enrolled in',
      sourceMultiplicity: '*',
      targetMultiplicity: '1..6',
      routing: 'straight',
    },
    {
      id: 'r_prof_auth',
      type: 'REALIZATION',
      sourceId: 'c_prof',
      targetId: 'c_interface',
      routing: 'straight',
    },
  ];

  // 2. USE CASE DIAGRAM
  const useCaseElements: DiagramElement[] = [
    {
      id: 'uc_boundary',
      type: 'SYSTEM_BOUNDARY',
      name: 'University Student Portal',
      x: 240,
      y: 60,
      width: 480,
      height: 520,
      style: {
        fillColor: '#F8FAFC',
        borderColor: '#94A3B8',
        textColor: '#334155',
        borderWidth: 2,
        borderStyle: 'dashed',
        opacity: 0.9,
        fontSize: 14,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'center',
      },
    },
    {
      id: 'uc_student',
      type: 'ACTOR',
      name: 'Undergraduate',
      x: 80,
      y: 180,
      width: 80,
      height: 100,
      style: {
        fillColor: '#E0F2FE',
        borderColor: '#0284C7',
        textColor: '#0F172A',
        borderWidth: 2,
        borderStyle: 'solid',
        opacity: 1,
        fontSize: 13,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'center',
      },
    },
    {
      id: 'uc_prof',
      type: 'ACTOR',
      name: 'Faculty Member',
      x: 80,
      y: 380,
      width: 80,
      height: 100,
      style: {
        fillColor: '#FEF3C7',
        borderColor: '#D97706',
        textColor: '#0F172A',
        borderWidth: 2,
        borderStyle: 'solid',
        opacity: 1,
        fontSize: 13,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'center',
      },
    },
    {
      id: 'uc_admin',
      type: 'ACTOR',
      name: 'System Admin',
      x: 790,
      y: 280,
      width: 80,
      height: 100,
      style: {
        fillColor: '#F3E8FF',
        borderColor: '#9333EA',
        textColor: '#0F172A',
        borderWidth: 2,
        borderStyle: 'solid',
        opacity: 1,
        fontSize: 13,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'center',
      },
    },
    {
      id: 'uc_enroll',
      type: 'USE_CASE',
      name: 'Register for Semester Courses',
      x: 340,
      y: 120,
      width: 250,
      height: 70,
      style: {
        fillColor: '#ECFDF5',
        borderColor: '#059669',
        textColor: '#064E3B',
        borderWidth: 2,
        borderStyle: 'solid',
        opacity: 1,
        fontSize: 13,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'center',
      },
    },
    {
      id: 'uc_prereq',
      type: 'USE_CASE',
      name: 'Validate Prerequisites',
      x: 400,
      y: 230,
      width: 210,
      height: 60,
      style: {
        fillColor: '#F0FDF4',
        borderColor: '#16A34A',
        textColor: '#14532D',
        borderWidth: 1.5,
        borderStyle: 'dashed',
        opacity: 1,
        fontSize: 12,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'center',
      },
    },
    {
      id: 'uc_grades',
      type: 'USE_CASE',
      name: 'Submit Final Semester Grades',
      x: 340,
      y: 360,
      width: 240,
      height: 70,
      style: {
        fillColor: '#FEFCE8',
        borderColor: '#CA8A04',
        textColor: '#713F12',
        borderWidth: 2,
        borderStyle: 'solid',
        opacity: 1,
        fontSize: 13,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'center',
      },
    },
    {
      id: 'uc_audit',
      type: 'USE_CASE',
      name: 'Audit Department Logs',
      x: 340,
      y: 470,
      width: 240,
      height: 65,
      style: {
        fillColor: '#FDF2F8',
        borderColor: '#DB2777',
        textColor: '#831843',
        borderWidth: 2,
        borderStyle: 'solid',
        opacity: 1,
        fontSize: 13,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'center',
      },
    },
  ];

  const useCaseRelationships: Relationship[] = [
    {
      id: 'ruc_1',
      type: 'ASSOCIATION',
      sourceId: 'uc_student',
      targetId: 'uc_enroll',
      routing: 'straight',
    },
    {
      id: 'ruc_2',
      type: 'INCLUDE',
      sourceId: 'uc_enroll',
      targetId: 'uc_prereq',
      label: '<<include>>',
      routing: 'straight',
    },
    {
      id: 'ruc_3',
      type: 'ASSOCIATION',
      sourceId: 'uc_prof',
      targetId: 'uc_grades',
      routing: 'straight',
    },
    {
      id: 'ruc_4',
      type: 'ASSOCIATION',
      sourceId: 'uc_admin',
      targetId: 'uc_audit',
      routing: 'straight',
    },
  ];

  // 3. ACTIVITY DIAGRAM
  const activityElements: DiagramElement[] = [
    {
      id: 'act_init',
      type: 'INITIAL_NODE',
      name: 'Start',
      x: 380,
      y: 60,
      width: 32,
      height: 32,
      style: {
        fillColor: '#0F172A',
        borderColor: '#0F172A',
        textColor: '#0F172A',
        borderWidth: 2,
        borderStyle: 'solid',
        opacity: 1,
        fontSize: 12,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'center',
      },
    },
    {
      id: 'act_login',
      type: 'ACTION',
      name: 'Enter Credentials & Request Course',
      x: 290,
      y: 130,
      width: 210,
      height: 60,
      style: {
        fillColor: '#F0F9FF',
        borderColor: '#0284C7',
        textColor: '#0F172A',
        borderWidth: 2,
        borderStyle: 'solid',
        opacity: 1,
        fontSize: 13,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'center',
      },
    },
    {
      id: 'act_decision',
      type: 'DECISION',
      name: 'Seats Available?',
      x: 365,
      y: 230,
      width: 60,
      height: 60,
      style: {
        fillColor: '#FEF9C3',
        borderColor: '#CA8A04',
        textColor: '#713F12',
        borderWidth: 2,
        borderStyle: 'solid',
        opacity: 1,
        fontSize: 12,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'center',
      },
    },
    {
      id: 'act_confirm',
      type: 'ACTION',
      name: 'Register Student & Issue Confirmation',
      x: 170,
      y: 350,
      width: 210,
      height: 60,
      style: {
        fillColor: '#ECFDF5',
        borderColor: '#059669',
        textColor: '#064E3B',
        borderWidth: 2,
        borderStyle: 'solid',
        opacity: 1,
        fontSize: 13,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'center',
      },
    },
    {
      id: 'act_waitlist',
      type: 'ACTION',
      name: 'Append to Automated Waitlist',
      x: 430,
      y: 350,
      width: 200,
      height: 60,
      style: {
        fillColor: '#FFFBEB',
        borderColor: '#D97706',
        textColor: '#78350F',
        borderWidth: 2,
        borderStyle: 'solid',
        opacity: 1,
        fontSize: 13,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'center',
      },
    },
    {
      id: 'act_merge',
      type: 'MERGE',
      name: 'Merge Flows',
      x: 375,
      y: 470,
      width: 40,
      height: 40,
      style: {
        fillColor: '#FEF9C3',
        borderColor: '#CA8A04',
        textColor: '#0F172A',
        borderWidth: 2,
        borderStyle: 'solid',
        opacity: 1,
        fontSize: 12,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'center',
      },
    },
    {
      id: 'act_final',
      type: 'FINAL_NODE',
      name: 'Complete',
      x: 378,
      y: 560,
      width: 34,
      height: 34,
      style: {
        fillColor: '#0F172A',
        borderColor: '#0F172A',
        textColor: '#0F172A',
        borderWidth: 2,
        borderStyle: 'solid',
        opacity: 1,
        fontSize: 12,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'center',
      },
    },
  ];

  const activityRelationships: Relationship[] = [
    {
      id: 'ar_1',
      type: 'CONTROL_FLOW',
      sourceId: 'act_init',
      targetId: 'act_login',
      routing: 'straight',
    },
    {
      id: 'ar_2',
      type: 'CONTROL_FLOW',
      sourceId: 'act_login',
      targetId: 'act_decision',
      routing: 'straight',
    },
    {
      id: 'ar_3',
      type: 'CONTROL_FLOW',
      sourceId: 'act_decision',
      targetId: 'act_confirm',
      label: '[yes, available]',
      routing: 'straight',
    },
    {
      id: 'ar_4',
      type: 'CONTROL_FLOW',
      sourceId: 'act_decision',
      targetId: 'act_waitlist',
      label: '[no, full]',
      routing: 'straight',
    },
    {
      id: 'ar_5',
      type: 'CONTROL_FLOW',
      sourceId: 'act_confirm',
      targetId: 'act_merge',
      routing: 'straight',
    },
    {
      id: 'ar_6',
      type: 'CONTROL_FLOW',
      sourceId: 'act_waitlist',
      targetId: 'act_merge',
      routing: 'straight',
    },
    {
      id: 'ar_7',
      type: 'CONTROL_FLOW',
      sourceId: 'act_merge',
      targetId: 'act_final',
      routing: 'straight',
    },
  ];

  // 4. SEQUENCE DIAGRAM
  const sequenceElements: DiagramElement[] = [
    {
      id: 'seq_student',
      type: 'LIFELINE',
      name: ':StudentClient',
      x: 120,
      y: 60,
      width: 140,
      height: 50,
      sequenceLifelineLength: 480,
      style: {
        fillColor: '#E0F2FE',
        borderColor: '#0284C7',
        textColor: '#0369A1',
        borderWidth: 2,
        borderStyle: 'solid',
        opacity: 1,
        fontSize: 13,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'center',
      },
    },
    {
      id: 'seq_gateway',
      type: 'LIFELINE',
      name: ':AuthGateway',
      x: 380,
      y: 60,
      width: 140,
      height: 50,
      sequenceLifelineLength: 480,
      style: {
        fillColor: '#FEF3C7',
        borderColor: '#D97706',
        textColor: '#B45309',
        borderWidth: 2,
        borderStyle: 'solid',
        opacity: 1,
        fontSize: 13,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'center',
      },
    },
    {
      id: 'seq_database',
      type: 'LIFELINE',
      name: ':Database',
      x: 640,
      y: 60,
      width: 140,
      height: 50,
      sequenceLifelineLength: 480,
      style: {
        fillColor: '#F3E8FF',
        borderColor: '#9333EA',
        textColor: '#7E22CE',
        borderWidth: 2,
        borderStyle: 'solid',
        opacity: 1,
        fontSize: 13,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'center',
      },
    },
  ];

  const sequenceRelationships: Relationship[] = [
    {
      id: 'sr_1',
      type: 'MESSAGE',
      sourceId: 'seq_student',
      targetId: 'seq_gateway',
      label: '1: submitCredentials(user, pass)',
      routing: 'straight',
    },
    {
      id: 'sr_2',
      type: 'MESSAGE',
      sourceId: 'seq_gateway',
      targetId: 'seq_database',
      label: '2: queryUserRecord(user)',
      routing: 'straight',
    },
    {
      id: 'sr_3',
      type: 'RETURN_MESSAGE',
      sourceId: 'seq_database',
      targetId: 'seq_gateway',
      label: '3: return UserHash',
      routing: 'straight',
    },
    {
      id: 'sr_4',
      type: 'RETURN_MESSAGE',
      sourceId: 'seq_gateway',
      targetId: 'seq_student',
      label: '4: return JWT Session Token',
      routing: 'straight',
    },
  ];

  // 5. STATE MACHINE DIAGRAM
  const stateElements: DiagramElement[] = [
    {
      id: 'st_init',
      type: 'INITIAL_STATE',
      name: 'Initial',
      x: 100,
      y: 120,
      width: 28,
      height: 28,
      style: {
        fillColor: '#0F172A',
        borderColor: '#0F172A',
        textColor: '#0F172A',
        borderWidth: 2,
        borderStyle: 'solid',
        opacity: 1,
        fontSize: 12,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'center',
      },
    },
    {
      id: 'st_draft',
      type: 'STATE',
      name: 'Draft Planning',
      x: 200,
      y: 100,
      width: 160,
      height: 70,
      notes: 'entry / loadCurriculum()\nexit / validateSchedule()',
      style: {
        fillColor: '#F0F9FF',
        borderColor: '#0284C7',
        textColor: '#0369A1',
        borderWidth: 2,
        borderStyle: 'solid',
        opacity: 1,
        fontSize: 13,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'center',
      },
    },
    {
      id: 'st_open',
      type: 'STATE',
      name: 'Enrolling (Open)',
      x: 440,
      y: 100,
      width: 170,
      height: 70,
      notes: 'do / monitorCapacity()',
      style: {
        fillColor: '#ECFDF5',
        borderColor: '#059669',
        textColor: '#064E3B',
        borderWidth: 2,
        borderStyle: 'solid',
        opacity: 1,
        fontSize: 13,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'center',
      },
    },
    {
      id: 'st_waitlist',
      type: 'STATE',
      name: 'Waitlisted',
      x: 440,
      y: 240,
      width: 170,
      height: 70,
      notes: 'entry / notifyPosition()',
      style: {
        fillColor: '#FFFBEB',
        borderColor: '#D97706',
        textColor: '#92400E',
        borderWidth: 2,
        borderStyle: 'solid',
        opacity: 1,
        fontSize: 13,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'center',
      },
    },
    {
      id: 'st_closed',
      type: 'STATE',
      name: 'Finalized & Locked',
      x: 700,
      y: 100,
      width: 180,
      height: 70,
      notes: 'entry / archiveRoster()',
      style: {
        fillColor: '#F8FAFC',
        borderColor: '#64748B',
        textColor: '#334155',
        borderWidth: 2,
        borderStyle: 'solid',
        opacity: 1,
        fontSize: 13,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'center',
      },
    },
    {
      id: 'st_final',
      type: 'FINAL_STATE',
      name: 'Archived',
      x: 940,
      y: 118,
      width: 34,
      height: 34,
      style: {
        fillColor: '#0F172A',
        borderColor: '#0F172A',
        textColor: '#0F172A',
        borderWidth: 2,
        borderStyle: 'solid',
        opacity: 1,
        fontSize: 12,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'center',
      },
    },
  ];

  const stateRelationships: Relationship[] = [
    {
      id: 'str_1',
      type: 'ASSOCIATION',
      sourceId: 'st_init',
      targetId: 'st_draft',
      label: 'startSemester',
      routing: 'straight',
    },
    {
      id: 'str_2',
      type: 'ASSOCIATION',
      sourceId: 'st_draft',
      targetId: 'st_open',
      label: 'publishRegistration',
      routing: 'straight',
    },
    {
      id: 'str_3',
      type: 'ASSOCIATION',
      sourceId: 'st_open',
      targetId: 'st_waitlist',
      label: 'capacityReached',
      routing: 'straight',
    },
    {
      id: 'str_4',
      type: 'ASSOCIATION',
      sourceId: 'st_waitlist',
      targetId: 'st_open',
      label: 'seatOpened',
      routing: 'straight',
    },
    {
      id: 'str_5',
      type: 'ASSOCIATION',
      sourceId: 'st_open',
      targetId: 'st_closed',
      label: 'addDropDeadline',
      routing: 'straight',
    },
    {
      id: 'str_6',
      type: 'ASSOCIATION',
      sourceId: 'st_closed',
      targetId: 'st_final',
      label: 'termCompleted',
      routing: 'straight',
    },
  ];

  const defaultCanvas = {
    width: 3200,
    height: 2400,
    backgroundColor: '#FFFFFF',
    gridEnabled: true,
    gridSize: 20,
    snapToGrid: true,
    zoom: 1,
    panX: 0,
    panY: 0,
    isDarkCanvas: false,
  };

  const diagrams: Diagram[] = [
    {
      id: 'd_class_1',
      projectId,
      name: 'Class Diagram - Domain Model',
      type: 'CLASS',
      elements: classElements,
      relationships: classRelationships,
      canvasSettings: { ...defaultCanvas },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'd_usecase_1',
      projectId,
      name: 'Use Case Diagram - Student Portal',
      type: 'USE_CASE',
      elements: useCaseElements,
      relationships: useCaseRelationships,
      canvasSettings: { ...defaultCanvas },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'd_activity_1',
      projectId,
      name: 'Activity Diagram - Course Enrollment',
      type: 'ACTIVITY',
      elements: activityElements,
      relationships: activityRelationships,
      canvasSettings: { ...defaultCanvas },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'd_seq_1',
      projectId,
      name: 'Sequence Diagram - Authentication',
      type: 'SEQUENCE',
      elements: sequenceElements,
      relationships: sequenceRelationships,
      canvasSettings: { ...defaultCanvas },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'd_state_1',
      projectId,
      name: 'State Machine - Course Lifecycle',
      type: 'STATE_MACHINE',
      elements: stateElements,
      relationships: stateRelationships,
      canvasSettings: { ...defaultCanvas },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ];

  return {
    id: projectId,
    name: 'University HR & Academic System',
    description: 'Enterprise architecture diagrams detailing course enrollments, faculty hierarchy, student workflows, and authentication lifelines.',
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date().toISOString(),
    diagrams,
  };
}
